---
- hosts: rh
  tasks:
  - name: date before
    command: date
    register: datebef
  - debug:
      var: datebef
  - name: sleep
    command: sleep 15
  - name: date
    command: date
    register: datereg
  - debug:
      var: datereg
